name: Release

on:
  push:
    branches: [ main ]
    paths:
      - 'pyproject.toml'

permissions:
  contents: write

jobs:
  check-version:
    runs-on: ubuntu-latest
    outputs:
      version_changed: ${{ steps.version.outputs.changed }}
      version: ${{ steps.version.outputs.version }}
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 2

    - name: Check if version changed
      id: version
      run: |
        # Get current version
        CURRENT_VERSION=$(grep -E "^version = " pyproject.toml | sed 's/version = "\(.*\)"/\1/')
        echo "Current version: $CURRENT_VERSION"

        # Get previous version
        git checkout HEAD~1 pyproject.toml 2>/dev/null || echo "No previous version"
        PREVIOUS_VERSION=$(grep -E "^version = " pyproject.toml 2>/dev/null | sed 's/version = "\(.*\)"/\1/' || echo "0.0.0")

        # Restore current version
        git checkout HEAD pyproject.toml

        echo "Previous version: $PREVIOUS_VERSION"

        if [ "$CURRENT_VERSION" != "$PREVIOUS_VERSION" ]; then
          echo "Version changed from $PREVIOUS_VERSION to $CURRENT_VERSION"
          echo "changed=true" >> $GITHUB_OUTPUT
          echo "version=$CURRENT_VERSION" >> $GITHUB_OUTPUT
        else
          echo "Version unchanged"
          echo "changed=false" >> $GITHUB_OUTPUT
        fi

  test:
    needs: check-version
    if: needs.check-version.outputs.version_changed == 'true'
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.13"

    - name: Install uv
      uses: astral-sh/setup-uv@v3

    - name: Install dependencies
      run: |
        pip install --upgrade pip uv
        uv pip install --system -e .[dev]

    - name: Run linter with auto-fix
      run: |
        uv run ruff check --fix .

    - name: Run import sorting
      run: |
        uv run isort .

    - name: Run type checking
      run: |
        uv run mypy .

    - name: Run tests
      run: |
        uv run pytest

  build-and-publish:
    needs: [check-version, test]
    if: needs.check-version.outputs.version_changed == 'true'
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.13"

    - name: Install uv
      uses: astral-sh/setup-uv@v3

    - name: Install build dependencies
      run: |
        uv pip install --system build twine

    - name: Build package
      run: |
        uv build

    - name: Check package
      run: |
        twine check dist/*

    # - name: Publish to PyPI
    #   env:
    #     TWINE_USERNAME: __token__
    #     TWINE_PASSWORD: ${{ secrets.PYPI_API_TOKEN }}
    #   run: |
    #     twine upload dist/*

    - name: Create GitHub Release
      uses: softprops/action-gh-release@v1
      with:
        tag_name: v${{ needs.check-version.outputs.version }}
        name: Release v${{ needs.check-version.outputs.version }}
        body: |
          Release v${{ needs.check-version.outputs.version }}

          Built package artifacts are attached to this release.
        files: dist/*
        draft: false
        prerelease: false
