name: Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.13"]

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      run: |
        pip install --upgrade pip uv
        uv pip install --system -e .[dev]

    - name: Run linter with auto-fix
      run: |
        ruff check --fix .

    - name: Run import sorting
      run: |
        isort .

    - name: Run type checking
      run: |
        mypy .

    - name: Run tests
      run: |
        pytest
